Tibre/msal update
Azure-Samples/active-directory-dotnet-webapi-onbehalfof pull request #35
Opened 2019-05-23 01:16 UTC by TiagoBrenck

- Updated sample to use MSAL
- For SPA project, updated the code to use msal.js and removed adal.js
- Modified Configure.ps1 to combine both client applications registration into one
- Updated .net framework version to 4.7

2019-05-24 07:29 UTC, kalyankrishna1 commented on README.md
> +- Then `TodoListService` also uses MSAL.NET  to get a token to act on behalf of the user to call the Microsoft Graph. For details, see [Service to service calls on behalf of the user](https://github.
>token [](start = 54, length = 5)

access token

2019-05-24 07:30 UTC, kalyankrishna1 commented on README.md
> +- Then `TodoListService` also uses MSAL.NET  to get a token to act on behalf of the user to call the Microsoft Graph. For details, see [Service to service calls on behalf of the user](https://github.
>token [](start = 54, length = 5)

access token

2019-05-24 07:30 UTC, kalyankrishna1 commented on README.md
> +- Then `TodoListService` also uses MSAL.NET  to get a token to act on behalf of the user to call the Microsoft Graph. For details, see [Service to service calls on behalf of the user](https://github.
>screen copy [](start = 425, length = 11)

screenshot

2019-05-24 07:31 UTC, kalyankrishna1 commented on README.md
> +Though we have three applications in the solution, you will notice that we only registred two applications in Azure AD. This is because Azure AD now allows multiple types of applications, like in thi
>registred [](start = 80, length = 9)

registered

2019-05-24 07:32 UTC, kalyankrishna1 commented on README.md
> +Though we have three applications in the solution, you will notice that we only registred two applications in Azure AD. This is because Azure AD now allows multiple types of applications, like in thi
>who share [](start = 250, length = 9)

to share

2019-05-24 07:32 UTC, kalyankrishna1 commented on README.md
> +This project represents the .NET desktop UI part of the flow, where users would sign-in and interact with the Web API. Also, this project is the consumer of information that is obtained from a downst
>another API [](start = 264, length = 11)

another API (Microsoft Graph)

2019-05-24 07:33 UTC, kalyankrishna1 commented on README.md
> +This project represents the .NET desktop UI part of the flow, where users would sign-in and interact with the Web API. Also, this project is the consumer of information that is obtained from a downst
>downstream WebAPI [](start = 193, length = 17)

downstream WebAPI (TodoListService)

2019-05-24 07:34 UTC, kalyankrishna1 commented on README.md
> +- We create an `IPublicClientApplication` using **MSAL Build Pattern** passing the `clientId` and `authority` in the builder. This `IPublicClientApplication` will be responsible of acquiring access t
>or id tokens [](start = 205, length = 12)

remove "or id tokens "

2019-05-24 07:35 UTC, kalyankrishna1 commented on README.md
> +     - demo_scope
>demo_scope [](start = 7, length = 10)

I dont think we actually used this? its just user_impersonation now, right?

2019-05-24 07:36 UTC, kalyankrishna1 commented on README.md
> +- We you use the `.default` scope, the end user is prompted for a combined set of permissions that include both the **TodoListService-OBO** and **Microsoft Graph**.
>include both [](start = 99, length = 12)

include scopes from both

2019-05-24 07:37 UTC, kalyankrishna1 commented on README.md
> +- `MsalUiRequiredException` will be thrown if there is no token for that user with the specified scope in the cache, or it got expired. This case requires the user to **SignIn** again.
>SignIn [](start = 169, length = 6)

Sign-In

2019-05-24 07:38 UTC, kalyankrishna1 commented on README.md
> +- Attaching the access token in the HTTP header as `Bearer` is mandatory when using [**On-Behalf-Of (OBO) flow**](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-on-behalf-o
>Attaching the access token in the HTTP header as `Bearer` is mandatory when using [**On-Behalf-Of (OBO) flow**](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-on-behalf-of-flow). [](start = 2, length = 205)

actually remove this line

2019-05-24 07:38 UTC, kalyankrishna1 commented on README.md
> +The **TodoListService** is our Web API project that will make a call to the downstream **Microsoft Graph API** using an access token obtained via the [**On-Behalf-Of (OBO) flow**](https://docs.micros
>a proper token [](start = 424, length = 14)

another access token

2019-05-24 07:39 UTC, kalyankrishna1 commented on README.md
> +- Notice that we are setting `SaveSigninToken` to `true` on the `TokenValidationParameters`. This is essential to get the `Bearer` token from the HTTP header using the identity bootstrap context: `Cl
>using [](start = 158, length = 5)

later using

2019-05-24 07:40 UTC, kalyankrishna1 commented on README.md
> +The one thing that you will notice is that we are using a different type of token cache provider, which cache tokens in a SQL Server database. It is incapsulated in the `MSALPerUserSqlTokenCacheProvi
>token cache provider [](start = 76, length = 20)

token cache provider in the WebAPI

2019-05-24 07:40 UTC, kalyankrishna1 commented on README.md
> +The one thing that you will notice is that we are using a different type of token cache provider, which cache tokens in a SQL Server database. It is incapsulated in the `MSALPerUserSqlTokenCacheProvi
>cache [](start = 104, length = 5)

caches

2019-05-24 07:41 UTC, kalyankrishna1 commented on README.md
> +The one thing that you will notice is that we are using a different type of token cache provider, which cache tokens in a SQL Server database. It is incapsulated in the `MSALPerUserSqlTokenCacheProvi
>It is [](start = 143, length = 5)

The implementation of this caching mechanism is

2019-05-24 07:41 UTC, kalyankrishna1 commented on README.md
> +- The `ConfidentialClientApplication` is built using the **Build Patten** introduced on MSAL v3.x, passing the `clientId`, `authority`, `appKey` and `redirectUri` on the builder. All of these values
>Patten [](start = 65, length = 6)

pattern

2019-05-24 07:42 UTC, kalyankrishna1 commented on README.md
> +- The `ConfidentialClientApplication` is built using the **Build Patten** introduced on MSAL v3.x, passing the `clientId`, `authority`, `appKey` and `redirectUri` on the builder. All of these values
>on [](start = 85, length = 2)

in

2019-05-24 07:42 UTC, kalyankrishna1 commented on README.md
> +- The `ConfidentialClientApplication` is built using the **Build Patten** introduced on MSAL v3.x, passing the `clientId`, `authority`, `appKey` and `redirectUri` on the builder. All of these values
>on [](start = 163, length = 2)

to

2019-05-24 07:42 UTC, kalyankrishna1 commented on README.md
> +- The `ConfidentialClientApplication` is built using the **Build Patten** introduced on MSAL v3.x, passing the `clientId`, `authority`, `appKey` and `redirectUri` on the builder. All of these values
>send [](start = 248, length = 4)

use

2019-05-24 07:45 UTC, kalyankrishna1 commented on TodoListClient/TokenCacheHelper.cs
> +	static class TokenCacheHelper
>TokenCacheHelper [](start = 14, length = 16)

comment the class

2019-05-24 07:46 UTC, kalyankrishna1 commented on TodoListService/Utils/ClaimConstraints.cs
> +	internal static class ClaimConstants
>ClaimConstants [](start = 23, length = 14)

File name should be ClaimConstants.cs

2019-05-24 18:17 UTC, TiagoBrenck commented on TodoListService/Utils/ClaimConstraints.cs
> +	internal static class ClaimConstants
File renamed

2019-05-24 18:18 UTC, TiagoBrenck commented on TodoListClient/TokenCacheHelper.cs
> +	static class TokenCacheHelper
Added comments

2019-05-28 09:54 UTC, jmprieur reviewed
Thanks @TiagoBrenck 
A couple of typos to fix, otherwise, LGTM

2019-05-28 09:54 UTC, jmprieur commented on README.md
> +This project represents the .NET desktop UI part of the flow, where users would sign-in and interact with the Web API (TodoListService). The API that this app calls ((TodoListService)) also requests
@TiagoBrenck, do we expect to have two sets of parenthesis?

2019-05-28 09:54 UTC, jmprieur commented on README.md
> +The **TodoListService** is our Web API project that will make a call to the downstream **Microsoft Graph API** using an access token obtained via the [**On-Behalf-Of (OBO) flow**](https://docs.micros
typo: acess  => access

2019-05-28 09:58 UTC, jmprieur requested changes
This sample is a v1.0 sample
why are you trying to update it to MSAL/v2.0 ?

cc: @kalyankrishna1 @TiagoBrenck

2019-05-28 09:58 UTC, jmprieur commented on AppCreationScripts/sample.json
> +    "Title": "Calling a downstream web API from another web API in Microsoft identity platform using the On-Behalf-Of flow",
This is a V1 sample, and it needs to remain v1.0

2019-05-28 09:58 UTC, jmprieur commented on README.md
> +### Scenario. How the sample uses MSAL.NET (and MSAL.js)
This is a v1.0 sample. It cannot use MSAL. It's still ADAL.

2019-05-28 22:06 UTC, TiagoBrenck commented
I have created a new PR on its proper repo, since we dont want to lose the v1 sample.
The new PR link is: https://github.com/Azure-Samples/ms-identity-aspnet-webapi-onbehalfof/pull/1

2019-05-29 03:52 UTC, kalyankrishna1 commented on README.md
> +The **TodoListService** is our Web API project that will make a call to the downstream **Microsoft Graph API** using an access token obtained via the [**On-Behalf-Of (OBO) flow**](https://docs.micros
typo "access"

---
In reply to: [287246996](https://github.com/Azure-Samples/active-directory-dotnet-webapi-onbehalfof/pull/35#discussion_r287246996) [](ancestors = 287246996)

2019-06-14 17:35 UTC, TiagoBrenck commented
The update was addressed here: https://github.com/Azure-Samples/ms-identity-aspnet-webapi-onbehalfof

2019-06-14 17:35 UTC, closed without merging